name: yusr
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0-134.1.beta <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  url_launcher:
  share_plus:
  flutter_keyboard_visibility: ^5.4.1
  animated_splash_screen: ^1.3.0
  page_transition:
  internet_connection_checker:
  provider:
  cupertino_icons: ^1.0.2
  shimmer:
  rive:
  maps_launcher:
  firebase_messaging:
  flutter_local_notifications:
  firebase_core:
  flutter_riverpod:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  foundation:
  image_path: "assets/images/yusr-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/


  fonts:
    - family: Almarai
      fonts:
        - asset: assets/BalooBhaijaan2-SemiBold.ttf
    - family: fonts
      fonts:
        - asset: assets/ScheherazadeNew-Regular.ttf



